services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - metadata-service

  metadata-service:
    build: ./content
    image: imdb-metadata
    environment:
      - TMDB_API_KEY= #YOUR API KEY
    ports:
      - "8000:8000"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
