services:
  server:
    build: ./server
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  

  postgres:
    image: postgres
    container_name: zync-postgres
    environment:
      - POSTGRES_USER: ${USER}
      - POSTGRES_PASSWORD: ${PASSWORD}
      - POSTGRES_DB: zyncdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
